#pragma once

#include "NativeGameplayTags.h"

/**
 * Native gameplay tags shared by every combat system.
 * States are counted on AActionCharacterBase so several systems can hold the same tag safely.
 */
namespace ActionGameTags
{
	// --- Character states ---
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_HitStun);
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Staggered);
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_KnockedDown);
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Invulnerable);
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_SuperArmor);
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Attacking);
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dodging);
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Aiming);
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Levitating);
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Slamming);
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_KineticLaunch);

	// --- Damage types (drive impact VFX/SFX selection) ---
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Blade);
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Bullet);
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Kinetic);
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Slam);
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Blunt);
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Energy);

	// --- Animation-driven combat events (sent by UAnimNotify_CombatEvent) ---
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Telegraph);
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_FireProjectile);
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_AreaImpact);
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_ChargeStart);
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_ChargeEnd);
}
